name: Main Job

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        run: echo "Récupération du code source"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Vérification terminée
        run: echo "Vérification terminée"
